### ISSUE TITLE
打开load core可以上网，全部退出就不能正常上网了吗，有时候想访问的网站需要国内ip...

### ISSUE THREAD

**Issue by Frida-Yan** [killgcd/justmysocks#12]

**Comment by bannedbook** [comment]
load core 是什么呢

**Comment by Frida-Yan** [comment]
![image](https://user-images.githubusercontent.com/32261261/85940839-91eded00-b951-11ea-8eee-f6165bf25ceb.png)
这个，问题解决了，退出后把本地的网络设置的代理关了就行

**Comment by bannedbook** [comment]
谢谢分享
