### ISSUE TITLE
jetbrains还是慢呀，idea插件都下不下来

### ISSUE THREAD

**Issue by YukiZou** [killgcd/justmysocks#13]
mac,youtube和twitter都挺流畅的，但是jetbrains还是慢，相关插件都下不下来。是我使用姿势有问题吗？以及justmysocks网站都登陆不上

**Comment by bannedbook** [comment]
jetbrains 不太了解，是使用系统代理，还是需要单独设置代理。
justmysocks网站  https://lihi1.com/cEsnp 好像不翻墙也可以上
