### ISSUE TITLE
付费之后my services点不开

### ISSUE THREAD

**Issue by plantu** [killgcd/justmysocks#14]
有点坑哦

**Comment by plantu** [comment]
看有说可以退款，
在 Just My Socks 官网菜单，选择 Services > My Services，
可是我点不进去my services退款都退不了，吐了

**Comment by bannedbook** [comment]
挂梯子 试试看如何

**Comment by plantu** [comment]
又找个梯子进去了，但是不知道该怎么用，
v2ray测试结果操作超时

**Comment by bannedbook** [comment]
其它节点 怎么样 呢 ，ss 节点

**Comment by plantu** [comment]
有木有什么花钱就能用的工具啊，

**Comment by plantu** [comment]
嗯嗯，我试了试ss节点，手机可以，电脑不行，
谢谢大佬~

**Comment by bannedbook** [comment]
电脑要启用一下 全局代理 ，是否启用了

**Comment by plantu** [comment]
嗯嗯，谢谢提醒！~
