### ISSUE TITLE
付款买了之后状态一直是等待中，需要等他变成Active吗

### ISSUE THREAD

**Issue by HendricksRichard** [killgcd/justmysocks#16]

**Comment by bannedbook** [comment]
服务状态是 Pending，那么请耐心等待一段时间，有时候可能因为风控的原因支付宝或 PayPal 的钱还没有打给 Just My Socks，虽然你已经完成了付款，但是 Just My Socks 还没有从支付宝方（或 PayPal）得到你完成付款的信息，因此需要等 Just My Socks 方确定已经完成了交易才能开通你的服务。

**Comment by HendricksRichard** [comment]
> 服务状态是 Pending，那么请耐心等待一段时间，有时候可能因为风控的原因支付宝或 PayPal 的钱还没有打给 Just My Socks，虽然你已经完成了付款，但是 Just My Socks 还没有从支付宝方（或 PayPal）得到你完成付款的信息，因此需要等 Just My Socks 方确定已经完成了交易才能开通你的服务。

PC端配置好了，就是太慢太慢了，网页加载不出来。安卓端配置应该没错，就是上不了Google，感觉也是网速的原因。
