### ISSUE TITLE
无法访问https://www.rakuten.co.jp

### ISSUE THREAD

**Issue by supertonylv** [killgcd/justmysocks#3]
使用的付费 Just My Socks ， 翻墙后能访问 www.google.com ,但是无法访问https://www.rakuten.co.jp

**Comment by bannedbook** [comment]
这个得给官方反应一下，
https://justmysocks2.net/members/submitticket.php?step=2&deptid=1
可以用google 翻译翻成英文反馈就行

**Comment by Rudy1XBStar** [comment]
> 使用的付费 Just My Socks ， 翻墙后能访问 [www.google.com](http://www.google.com) ,但是无法访问https://www.rakuten.co.jp

**Comment by bannedbook** [comment]
用哪个客户端，有的客户端可以做一些设置。
比如把路由设置成全局
