### ISSUE TITLE
速度极慢

### ISSUE THREAD

**Issue by asjwb** [killgcd/justmysocks#7]
看着别人的youtube测评视频，速度都能到好几万k，可自己的即使最快才就四五千k，甚至有时候就几十k，基本也就停留在看网页上，看大纪元连图都加载半天，到底怎么回事啊，3线路最快，可也这个情况

**Comment by bannedbook** [comment]
跟个人网络环境也有一定关系
如果实在速度不满意，可以如果购买后试用不满意，可申请退款：Just My Socks 怎么退款（退款条件）https://github.com/killgcd/justmysocks/blob/master/jmstk.md
