### ISSUE TITLE
配置正确，JMS的五个地址都无法使用，是怎么回事啊

### ISSUE THREAD

**Issue by dis-xcl** [killgcd/justmysocks#8]
您好，请问一下，Just My Socks发给我的五个地址和IP都无法使用，配置没有问题，使用的是Shadowsocks客户端，之前使用别的都正常！这它给的五个都无法使用，配置好了，网页都无法打开，是怎么回事，怎么解决呀？

**Comment by bannedbook** [comment]
有一个需要安装 simple obfs 插件，确保安装了这个插件。
五个地址和IP都无法使用，这个比较奇怪。
确保开启了全局代理模式
如果还不行，你把他五个地址emai看看banned.ebook@gmail.com

**Comment by hejiafeng** [comment]
> 您好，请问一下，Just My Socks发给我的五个地址和IP都无法使用，配置没有问题，使用的是Shadowsocks客户端，之前使用别的都正常！这它给的五个都无法使用，配置好了，网页都无法打开，是怎么回事，怎么解决呀？

能用吗？

**Comment by bannedbook** [comment]
注意：如果购买后试用不满意，可申请退款：[Just My Socks 怎么退款（退款条件）](https://github.com/killgcd/justmysocks/blob/master/jmstk.md)

**Comment by mahu8766** [comment]
同问啊 为啥地址都不行啊

**Comment by bannedbook** [comment]
可以做个端口测试  https://ssr.tools/1164
如果端口测试正常，一般是自己的问题
