### ISSUE TITLE
GIA网络不可用

### ISSUE THREAD

**Issue by cyjj** [killgcd/justmysocks#9]
在service页面里面显示的c25s3.jamjams.net | v2ray是不是说这个GIA网络只能通过v2ray呢？我按照页面上的说明配置了ss不能连接，但是用v2ray就可以使用，这是什么原因呢？

**Comment by bannedbook** [comment]
是的，第三组服务器现在是 V2Ray ，需要v2ray 客户端 连接

**Comment by bannedbook** [comment]
可以试试这个客户端
https://play.google.com/store/apps/details?id=free.shadowsocks.proxy.VPN
同时支持 ss和v2ray

**Comment by cyjj** [comment]
mac和ios有推荐的嘛~~~

**Comment by bannedbook** [comment]
https://github.com/killgcd/justmysocks
文章最后有 下载客户端的介绍
